# Generated by Django 2.2.9 on 2021-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_auto_20210903_1614'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='unique_following'),
        ),
        migrations.AlterModelTable(
            name='follow',
            table='following',
        ),
    ]
