# Generated by Django 2.2.9 on 2021-09-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20210905_1148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='follow',
            table='follow',
        ),
    ]
